baseURL: "https://dcebotarenco.github.io/"
languageCode: "en-us"
title: "dcebotarenco"
theme: "PaperMod"
paginate: 5
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

disqusShortname: dcebotarenco-github-io

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: dcebotarenco
  description: "a Blog about coding in Java and others"
  keywords: [Blog, Portfolio, dcebotarenco]
  author: dcebotarenco
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: true
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "icon.png"
    favicon16x16: "icon.png"
    favicon32x32: "icon.png"
    apple_touch_icon: "icon.png"
    safari_pinned_tab: "icon.png"

  label:
    text: "dcebotarenco"
    icon: 'icon.png'
    iconHeight: 35

  profileMode:
    enabled: true
    title: "\\>> Hello, I'm Dan 👋"
    subTitle: Java developer, father
    imageUrl: 'profile-picture.jpeg'
    
  socialIcons:
    - name: linkedin
      url: 'https://www.linkedin.com/in/dcebotarenco'
    - name: twitter
      url: "https://twitter.com/dancebotarenco"
    - name: github
      url: "https://github.com/dcebotarenco"

  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    anchorLineNos: true
    codeFences: true
    guessSyntax: true
    # lineNos: true
    style: monokai

# Site-wide navigation
menu:
  main:
    - weight : 1
      identifier : "about"
      name : "About"
      title : "About"
      url : "/about/"
    - weight : 2
      identifier : "blog"
      name : "Blog"
      title : "Blog"
      url : "/posts/"
    - weight: 3
      name: Search
      url: /search/

